import { describe, it, expect, vi, beforeEach } from "vitest";
import { get } from "svelte/store";
import {
  resizeDebugState,
  initResizeDebug,
  logResizeDebug,
  isResizeDebugEnabled,
  setResizeDebugEnabled,
  toggleResizeDebug,
  clearResizeDebug,
  setResizeDebugSnapshot,
  formatDebugError,
} from "./resizeDebug.js";

beforeEach(() => {
  // Reset the store to a clean state between tests.
  // initResizeDebug guards with a module-level `initialized` flag, so we
  // manipulate the store directly to get a fresh baseline.
  resizeDebugState.set({
    enabled: true,
    startedAt: 1000,
    nextId: 1,
    events: [],
    snapshot: null,
  });
});

describe("formatDebugError", () => {
  it("extracts name and message from Error instances", () => {
    const err = new TypeError("bad value");
    expect(formatDebugError(err)).toEqual({ name: "TypeError", message: "bad value" });
  });

  it("wraps a plain string in a message object", () => {
    expect(formatDebugError("oops")).toEqual({ message: "oops" });
  });

  it("serializes plain objects via JSON round-trip", () => {
    expect(formatDebugError({ code: 42 })).toEqual({ code: 42 });
  });

  it("converts other primitives via String()", () => {
    expect(formatDebugError(123)).toEqual({ message: "123" });
    expect(formatDebugError(null)).toEqual({ message: "null" });
    expect(formatDebugError(undefined)).toEqual({ message: "undefined" });
  });
});

describe("logResizeDebug", () => {
  it("appends an event with incrementing IDs", () => {
    logResizeDebug("test:a", { x: 1 });
    logResizeDebug("test:b", { y: 2 });

    const state = get(resizeDebugState);
    expect(state.events).toHaveLength(2);
    expect(state.events[0].id).toBe(1);
    expect(state.events[0].type).toBe("test:a");
    expect(state.events[1].id).toBe(2);
    expect(state.events[1].type).toBe("test:b");
  });

  it("does not log when disabled", () => {
    setResizeDebugEnabled(false);
    // Clear events generated by setResizeDebugEnabled itself
    resizeDebugState.update((s) => ({ ...s, events: [] }));

    logResizeDebug("test:ignored");
    expect(get(resizeDebugState).events).toHaveLength(0);
  });

  it("sanitizes detail values (truncates numbers to 2 decimals)", () => {
    logResizeDebug("test:num", { pi: 3.14159265 });
    const event = get(resizeDebugState).events.at(-1)!;
    expect(event.details.pi).toBe(3.14);
  });
});

describe("isResizeDebugEnabled / setResizeDebugEnabled / toggleResizeDebug", () => {
  it("reports the current enabled state", () => {
    expect(isResizeDebugEnabled()).toBe(true);

    setResizeDebugEnabled(false);
    expect(isResizeDebugEnabled()).toBe(false);
  });

  it("toggles the enabled state", () => {
    expect(isResizeDebugEnabled()).toBe(true);
    toggleResizeDebug();
    expect(isResizeDebugEnabled()).toBe(false);
    toggleResizeDebug();
    expect(isResizeDebugEnabled()).toBe(true);
  });
});

describe("clearResizeDebug", () => {
  it("resets events and nextId", () => {
    logResizeDebug("test:one");
    logResizeDebug("test:two");
    expect(get(resizeDebugState).events.length).toBeGreaterThanOrEqual(2);

    clearResizeDebug();
    const state = get(resizeDebugState);
    // clearResizeDebug itself logs a "debug:cleared" event
    expect(state.events).toHaveLength(1);
    expect(state.events[0].type).toBe("debug:cleared");
  });
});

describe("setResizeDebugSnapshot", () => {
  it("stores the snapshot when enabled", () => {
    const snapshot = {
      reason: "test",
      windowInnerHeight: 500,
      visualViewportHeight: 500,
      lastWindowH: 400,
      maxWindowH: 800,
      popScrollHeight: 300,
      popClientHeight: 300,
      popOffsetHeight: 300,
      bodyScrollHeight: 500,
      bodyClientHeight: 500,
      docClientHeight: 500,
    };
    setResizeDebugSnapshot(snapshot);
    expect(get(resizeDebugState).snapshot).toEqual(snapshot);
  });

  it("does not store snapshot when disabled", () => {
    setResizeDebugEnabled(false);
    setResizeDebugSnapshot({
      reason: "should-not-store",
      windowInnerHeight: 0,
      visualViewportHeight: null,
      lastWindowH: 0,
      maxWindowH: 0,
      popScrollHeight: null,
      popClientHeight: null,
      popOffsetHeight: null,
      bodyScrollHeight: null,
      bodyClientHeight: null,
      docClientHeight: null,
    });
    expect(get(resizeDebugState).snapshot).toBeNull();
  });
});
